// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PredictaPay.Infrastructure.Data;

#nullable disable

namespace PredictaPay.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418040937_InitialIntIdsSchema")]
    partial class InitialIntIdsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("PredictaPay.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 3, 19, 3, 47, 42, 860, DateTimeKind.Utc).AddTicks(6430),
                            Email = "john@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "AQAAAAIAAYagAAAAENptXfHm/1aTmuwLuGUoG78eSrRuQLrOfsXKEk1iMO8UXwG0mBLgtUEpid9cz5O5Qw==",
                            Role = "User"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 3, 29, 3, 47, 42, 966, DateTimeKind.Utc).AddTicks(470),
                            Email = "jane@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "AQAAAAIAAYagAAAAEKHbVV6MCS3u4bp103KbyBB7uYL0RNkbUY8RA1x/StTJQtXuzNT2oZ2fQZ369trCNA==",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("PredictaPay.Domain.Entities.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecurrenceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BillId");

                    b.HasIndex("UserId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            BillId = 1,
                            Amount = 125.50m,
                            BillName = "Electricity Bill",
                            Category = "Utilities",
                            CreatedAt = new DateTime(2026, 4, 8, 3, 47, 42, 983, DateTimeKind.Utc).AddTicks(330),
                            DueDate = new DateOnly(2026, 4, 22),
                            Notes = "Monthly electric bill",
                            RecurrenceType = 2,
                            Status = 0,
                            UserId = 1
                        },
                        new
                        {
                            BillId = 2,
                            Amount = 79.99m,
                            BillName = "Internet Bill",
                            Category = "Utilities",
                            CreatedAt = new DateTime(2026, 4, 3, 3, 47, 42, 983, DateTimeKind.Utc).AddTicks(1010),
                            DueDate = new DateOnly(2026, 4, 20),
                            Notes = "Monthly internet service",
                            RecurrenceType = 2,
                            Status = 0,
                            UserId = 1
                        },
                        new
                        {
                            BillId = 3,
                            Amount = 150.00m,
                            BillName = "Car Insurance",
                            Category = "Insurance",
                            CreatedAt = new DateTime(2026, 4, 13, 3, 47, 42, 983, DateTimeKind.Utc).AddTicks(1030),
                            DueDate = new DateOnly(2026, 4, 27),
                            Notes = "Auto insurance premium",
                            RecurrenceType = 2,
                            Status = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PredictaPay.Domain.Entities.Reminder", b =>
                {
                    b.Property<int>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReminderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReminderType")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReminderId");

                    b.HasIndex("BillId");

                    b.ToTable("Reminders");

                    b.HasData(
                        new
                        {
                            ReminderId = 1,
                            BillId = 1,
                            IsSent = false,
                            ReminderDate = new DateTime(2026, 4, 20, 3, 47, 42, 983, DateTimeKind.Utc).AddTicks(5470),
                            ReminderType = 0
                        },
                        new
                        {
                            ReminderId = 2,
                            BillId = 2,
                            IsSent = false,
                            ReminderDate = new DateTime(2026, 4, 19, 3, 47, 42, 983, DateTimeKind.Utc).AddTicks(7600),
                            ReminderType = 2
                        },
                        new
                        {
                            ReminderId = 3,
                            BillId = 3,
                            IsSent = true,
                            ReminderDate = new DateTime(2026, 4, 25, 3, 47, 42, 983, DateTimeKind.Utc).AddTicks(7610),
                            ReminderType = 0
                        });
                });

            modelBuilder.Entity("PredictaPay.Domain.Entities.Bill", b =>
                {
                    b.HasOne("PredictaPay.Domain.Entities.AppUser", "User")
                        .WithMany("Bills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PredictaPay.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("PredictaPay.Domain.Entities.Bill", "Bill")
                        .WithMany("Reminders")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("PredictaPay.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("PredictaPay.Domain.Entities.Bill", b =>
                {
                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
